<div class="des-detailProduct"><?= $this->getProduct()->getShortDescription(); ?></div>

<?php
$video = $this->getProduct()->getVideoLink();
$_video = false;
if(isset($video) && !is_null($video)) {
    $_video = $video;
    if (strpos($video, 'youtube') > 0||strpos($video, 'youtu.be') >0) {
        preg_match("#(?<=v=)[a-zA-Z0-9-]+(?=&)|(?<=v\/)[^&\n]+(?=\?)|(?<=v=)[^&\n]+|(?<=youtu.be/)[^&\n]+#", $video, $matches);
        $_video = 'https://www.youtube.com/embed/' . $matches[0];
    }
}
?>

<?php if ($_video) { ?>
    <p id="tit-training-detail" class="subTitDetailPage">TRAINING VIDEO</p>
    <div id="videoDetailPage">
        <iframe width="100%" height="100%" src="<?= $_video ?>" frameborder="0" allowfullscreen></iframe>
    </div>
<?php } ?>

<div id="element">
    <div data-role="title">
        <p class="subTitDetailPage" style="cursor: pointer">Additional Information</p>
    </div>
    <div class="des-detailProduct" data-role="content"><?= $this->getProduct()->getDescription(); ?></div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'tabs'], function ($) {
        $("#element").collapsible();
    });
</script>
<div class="clearfix pad40"></div>
