<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
?>

<!-- 3 Categories  -->
<div class="row threeCategory">
    <div class="col-xs-12 col-sm-4">
        <a href="/products/piezoart-electric.html">
            <img class="img-full" src="<?= $mediaUrl . 'images/home/ct1.jpg' ?>"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-4">
        <a href="/products/signature-series.html">
            <img class="img-full" src="<?= $mediaUrl . 'images/home/ct2.jpg' ?>"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-4">
        <a href="/products/recommended-kits-650.html">
            <img class="img-full" src="<?= $mediaUrl . 'images/home/ct3.jpg' ?>"/>
        </a>
    </div>
</div>
<div class="clearfix pad30"></div>

<?php // Get Latest Products
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $_objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$latest = $productCollection->create()
    ->addAttributeToSelect('*')
    ->addFieldToFilter("status", "1")
    ->setOrder('created_at', 'DESC')
    ->setPageSize(20)
    ->load();
?>

<?php if (isset($latest) && $latest->getSize() > 0) { ?>
<!-- New Products -->
<p class="head-homePage">NEW PRODUCTS</p>
<div id="newProductHS" class="carousel slide" data-ride="carousel" data-interval="false">
    <!-- Wrapper for slides -->
    <div class="carousel-inner padHS " role="listbox">
        <!-- Items -->
        <?php $i = 1; ?>
        <?php foreach($latest as $newPro) { ?>
            <?php if ($i % 4 == 1) { ?>
            <div class="item <?= ($i == 1)?' active':'' ?>">
                <div class="row">
            <?php } ?>

                    <div class="col-xs-6 col-sm-3">
                        <div class="HS-item-wrap">
                            <a href="<?= $newPro->getProductUrl() ?>">
                                <div class="img-resp img100">
                                    <img src="<?= $mediaUrl .'catalog/product'. $newPro->getThumbnail() ?>" />
                                </div>
                                <p><?= $newPro->getName() ?></p>
                            </a>
                        </div>
                    </div>
            <?php if ($i % 4 == 0 || $i == $latest->getSize()) { ?>
                </div>
            </div>
            <?php } ?>
            <?php $i++; ?>
        <?php } ?>
    </div>
    <!-- Controls -->
    <a href="#newProductHS" role="button" data-slide="prev">
        <div class="prevButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/left.png"/>
        </div>
    </a>
    <a href="#newProductHS" role="button" data-slide="next">
        <div class="nextButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/right.png"/>
        </div>
    </a>
</div>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            $(window).load(function () {
                $('#newProductHS').carousel({
                    interval: false
                });
            });
        });
    });
</script>
<div class="clearfix pad100"></div>
<?php } ?>


<!-- Promotional Products -->
<?php // Get Promotional Products
$categoryFactory = $_objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$promotionCategory = $categoryFactory->create()
    ->addAttributeToFilter('url_key','promotional')
    ->addAttributeToSelect('*')
    ->getFirstItem();

$promotionCollection = $_objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$promo = $promotionCollection->create()
    ->addAttributeToSelect('*')
    ->addCategoryFilter($promotionCategory)
    ->addAttributeToFilter('status', '1')
    ->setOrder('created_at', 'DESC')
    ->setPageSize(20)
    ->load();
?>

<?php if ($promo->getSize() > 0) { ?>
<p class="head-homePage">PROMOTIONAL PRODUCTS</p>
<div id="proProductHS" class="carousel slide" data-ride="carousel" data-interval="false">
    <!-- Wrapper for slides -->
    <div class="carousel-inner padHS " role="listbox">
    <?php $i = 1; ?>
    <?php foreach($promo as $item) { ?>
        <?php if ($i % 4 == 1) { ?>
            <div class="item <?= ($i == 1)?' active':'' ?>">
                <div class="row">
        <?php } ?>

        <div class="col-xs-6 col-sm-3">
            <div class="HS-item-wrap">
                <a href="<?= $item->getProductUrl() ?>">
                    <div class="img-resp img100">
                        <img src="<?= $mediaUrl .'catalog/product'. $item->getThumbnail() ?>" />
                    </div>
                    <p><?= $item->getName() ?></p>
                </a>
            </div>
        </div>
        <?php if ($i % 4 == 0 || $i == $promo->getSize()) { ?>
                </div>
            </div>
        <?php } ?>
        <?php $i++; ?>
    <?php } ?>
    </div>
    <!-- Controls -->
    <a href="#proProductHS" role="button" data-slide="prev">
        <div class="prevButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/left.png"/>
        </div>
    </a>
    <a href="#proProductHS" role="button" data-slide="next">
        <div class="nextButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/right.png"/>
        </div>
    </a>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            $(window).load(function () {
                $('#proProductHS').carousel({
                    interval: false
                });
            });
        });
    });
</script>
<?php } ?>