<style type="text/css">
    @media only screen and (max-width: 767px) {
        .breadcrumbs, .page-title-wrapper {
            display: none;
        }
    }
</style>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

//$categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
//$productsCate = $categoryFactory->create()
//    ->addAttributeToFilter('url_key','products')
//    ->addAttributeToSelect('*')
//    ->getFirstItem();
//
//$categoryModel = $objectManager->create('\Magento\Catalog\Model\Category');
//$result = $categoryModel->getCategories($productsCate->getId());

// Get Menu
$menu = $objectManager->get('\Magento\Theme\Block\Html\Topmenu');
$columnsLimit = $menu->getColumnsLimit() ?: 0;
$_menu = $menu->getHtml('level-top', 'submenu', $columnsLimit);

 // Get Current Category name
$registry = $objectManager->create('Magento\Framework\Registry');
$currentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
?>

<h4 class="titleLeftSidebarXs visible-xs" ><?= $currentCategory->getName()?></h4>
<div class="menuLeftSidebar">
    <h4 class="titleLeftSidebar hidden-xs">CATEGORY</h4>
    <div class="leftMenuDiv">
        <ul id="leftMenuUl">
            <?= $_menu ?>
        </ul>
    </div>
</div>
<div class="clearfix pad30"></div>

<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
        $( document ).ready(function() {
            $('#leftMenuUl li.parent').each(function() {
                var data = $(this).hasClass("has-active") ? "-" : "+";
                $(this).prepend('<span class="dropLeftMenu">'+data+'</span>');
            });

            $('#leftMenuUl .dropLeftMenu').click(function(){

                var selectCt = $(this).parent().find('ul.submenu').first();
                if (selectCt.is(':visible')) {
                    $(this).text("+");
                    selectCt.slideUp('normal');
                } else {
                    $(this).text("-");
                    selectCt.slideDown('normal');
                }
            });


        })
    });
</script>

