<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
?>


<div id="bannerHS" class="carousel slide" data-ride="carousel" data-interval="false">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <!-- Items -->
        <div class="item active">
            <img src="<?= $mediaUrl ?>images/banner/1.jpg" />
        </div>
        <div class="item">
            <img src="<?= $mediaUrl ?>images/banner/2.jpg" />
        </div>
        <div class="item">
            <img src="<?= $mediaUrl ?>images/banner/3.jpg" />
        </div>
        <div class="item">
            <img src="<?= $mediaUrl ?>images/banner/4.jpg" />
        </div>
    </div>
    <!-- Controls -->
    <a href="#bannerHS" role="button" data-slide="prev">
        <div class="prevButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/left-big.png"/>
        </div>
    </a>
    <a href="#bannerHS" role="button" data-slide="next">
        <div class="nextButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/right-big.png"/>
        </div>
    </a>

    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#bannerHS" data-slide-to="0" class="active"></li>
        <li data-target="#bannerHS" data-slide-to="1"></li>
        <li data-target="#bannerHS" data-slide-to="2"></li>
        <li data-target="#bannerHS" data-slide-to="3"></li>
    </ol>
</div>


<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            $(window).load(function () {
                $('#bannerHS').carousel({
                    interval: false
                });
            });
        });
    });
</script>
