<?php
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of \Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$videoObj = $_objectManager->get('Sahy\Banner\Block\Frontend\Banners');
$videos = $videoObj->getVideoContent();
?>


<?php
$vidObj = $_objectManager->get('Magestore\Bannerslider\Block\Bannerslider');
$data = $vidObj->getSliderCollection();
?>

<div class="clearfix pad20"></div>
<div class="row">
    <div class="col-xs-12 col-sm-5 col-md-3">
        <h4 class="titleLeftSidebar">CATEGORY</h4>
        <?php $i = 1; ?>
        <div class="leftMenuVideo">
        <?php foreach($data as $category) { ?>
            <a href="javascript:void(0);" class="clickCategoryTrainingVideo ctTrainingVideo <?= ($i == 1) ? 'active':'' ?>"
                data-id="<?= '#listTrainingVideo_' . $category["id"] ?>">
                <?= $category['title'] ?>
            </a>
            <div class="clearfix <?= ($i == count($data)) ? '':'pad10' ?>"></div>
            <?php $i++; ?>
        <?php } ?>
        </div>
        <div class="clearfix pad20 visible-xs"></div>
    </div>
    <div class="col-xs-12 col-sm-7 col-md-9">
        <p class="headingTrainVideo">TRAINING VIDEO</p>
        <?php $j = 1; ?>
        <?php foreach($data as $category) { ?>
        <div class="row trainVideoRow <?= ($j == 1) ? 'active':'' ?>" id="listTrainingVideo_<?= $category['id'] ?>">
            <?php if (is_null($category["collection"]) || count($category["collection"]) == 0 ) { ?>
                <p style="padding: 0 15px">There is no video.</p>
            <?php } ?>
            <?php foreach($category["collection"] as $item) { ?>
                <div class="videoItemWrap" id="train_video_<?= $item['id'] ?>">
                    <?php
                    if ($item['image']) $img = $mediaUrl . $item['image'];
                    $videoLink = trim($item['url']);
                    if(isset($videoLink) && !is_null($videoLink)) {
                        if (strpos($videoLink, 'youtube') > 0 || strpos($videoLink, 'youtu.be' ) >0) {
                            preg_match("#(?<=v=)[a-zA-Z0-9-]+(?=&)|(?<=v\/)[^&\n]+(?=\?)|(?<=v=)[^&\n]+|(?<=youtu.be/)[^&\n]+#", $videoLink, $matches);
                            $videoLink = 'https://www.youtube.com/embed/' . $matches[0];
                            if (is_null($item['image'])) {
                                $img = 'http://img.youtube.com/vi/'.$matches[0].'/0.jpg';
                            }
                        }
                    }
                    ?>
                    <a href="javascript:void(0);" class="clickVideo" data-video="<?= $videoLink ?>">
                        <div class="videoItem">
                            <div class="img-resp noBg" style="padding-bottom: 75%">
                                <img class="img-full" src="<?= $img ?>" />
                            </div>
                            <p class="titTrainVideo"><?= $item['name'] ?></p>
                        </div>
                    </a>
                </div>
            <?php } ?>
        </div>
        <?php $j++; ?>
        <?php } ?>
    </div>
</div>

<div id="popUpTraining">
    <div id="trainingVideoWrap">
        <a id="closePopUpTraining">[ x ]</a>
        <div id="respTrainingVideo">
            <iframe width="100%" height="100%" src="" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function () {
            // Click category
            $('.clickCategoryTrainingVideo').click(function(){
                $('.trainVideoRow').removeClass('active');
                $($(this).attr('data-id')).addClass('active');
                $('.ctTrainingVideo').removeClass('active');
                $(this).addClass('active');

            });

            // Click Training video
            $('.clickVideo').click(function () {
                var videoLink =  $(this).attr('data-video');
                if (videoLink != "") {
                    $('#respTrainingVideo > iframe').attr("src",videoLink);
                    $('#popUpTraining').addClass("open");
                }
            });
            // Click close pop-up
            $('#closePopUpTraining').click(function() {
                $('#popUpTraining').removeClass("open");
                $('#respTrainingVideo > iframe').attr("src","");
            })
        });
    })
</script>
