<div id="popUpTraining">
    <div id="trainingVideoWrap">
        <a id="closePopUpTraining">[ x ]</a>
        <div id="respTrainingVideo">
            <iframe width="100%" height="100%" src="" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>

<!-- Quick View -->
<div class="containerPopUpWrap" id="">
    <div class="popUpInnerWrap">
        <a href="javascript:void(0);" id="closeQuickViewAction">Close the window [x]</a>
        <div class="clearfix"></div>
        <div id="dataQuickView">
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="leftImg">
                        <img id="imgQuickView" src="" />
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <a href="#" id="titQuickView"></a>
                    <p id="skuQuickView"></p>
                    <p id="priceQuickView"></p>
                    <div id="addToCartQuickView">
                        <form data-role="tocart-form" action="" method="post">
                            <input class="productWV" type="hidden" name="product" value="3">
                            <input class="uencWV" type="hidden" name="" value="">
                            <input class="formKeyWV" name="form_key" type="hidden" value="">
                            <button type="submit" title="Add to Cart" class="action tocart primary">
                                <span>Add to Cart</span>
                            </button>
                        </form>
                    </div>
                    <div class="lineQuickView"></div>
                    <div id="desQuickView"></div>
                </div>
            </div>
        </div>
    </div>
</div>