<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<!-- Google Map -->
<div id="ggMapWrap" style="text-decoration:none; overflow:hidden; width:100%; max-width:100%;">
    <div id="gmap_canvas" style="height:100%; width:100%;max-width:100%;">
        <iframe style="height:100%;width:100%;border:0;" frameborder="0"
                src="https://www.google.com/maps/embed/v1/directions?origin=9287+East+9th+Street,+Rancho+Cucamonga,+CA+91730,+USA&destination=9287+East+9th+Street,+Rancho+Cucamonga,+CA+91730,+USA&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe>
    </div>
</div>
<style type="text/css">
    #gmap_canvas img {
        max-width: none !important;
        background: none !important;
    }
</style>
<!-- # Google Map -->

<div class="row" id="contact-wrapper">
    <div class="col-xs-12 col-sm-4 col-md-6" id="cont_left_info">
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact-info')->toHtml();?>
        <div class="clearfix pad20 visible-xs"></div>

    </div>

    <div class="col-xs-12 col-sm-8 col-md-6" id="cont_right_form">
        <form class="form contact"
              action="<?php /* @escapeNotVerified */
              echo $block->getFormAction(); ?>"
              id="contact-form"
              method="post"
              data-hasrequired="<?php /* @escapeNotVerified */
              echo __('* Required Fields') ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div><span class="cont_head"><?php /* @escapeNotVerified */
                        echo __('CONTACT FORM') ?></span></div>

                <div class="field name required">
                    <label class="label" for="name"><span><?php /* @escapeNotVerified */
                            echo __('Your Name:') ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?php /* @escapeNotVerified */
                        echo __('Your Name') ?>"
                               value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
                               class="input-text" type="text" data-validate="{required:true}"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */
                            echo __('Your Email:') ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?php /* @escapeNotVerified */
                        echo __('Your Email') ?>"
                               value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>"
                               class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="field telephone">
                    <label class="label" for="telephone"><span><?php /* @escapeNotVerified */
                            echo __('Your Subject:') ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */
                        echo __('Your Subject') ?>" value="" class="input-text" type="text"/>
                    </div>
                </div>
                <div class="field comment required">
                    <label class="label" for="comment"><span><?php /* @escapeNotVerified */
                            echo __('Your Message:') ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */
                        echo __('Your Message') ?>" class="input-text" cols="5" rows="3"
                                  data-validate="{required:true}"></textarea>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <button type="submit" title="<?php /* @escapeNotVerified */
                    echo __('SEND') ?>" class="action submit primary">
                        <span><?php /* @escapeNotVerified */
                            echo __('SEND') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>

</div>