<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$limit = 12;
$title = __('We found other products you might like!');
$canItemsAddToCart = false;
$items = false; $image = false;

$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);


switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('RELATED PRODUCTS');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $canItemsAddToCart = false;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('RELATED PRODUCTS');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        $exist = false;
        break;

    default:
        $exist = false;
        break;
}
?>



<?php if ($exist): ?>
<div id="relatedSliderWrapper">
    <?php if ($type == 'related' || $type == 'upsell'): ?>
<p class="head-homePage"><?= $title; ?></p>
<div id="relatedSlider" class="carousel slide <?= $class ?>" data-ride="carousel" data-interval="false"
    data-limit="<?= $limit ?>">
    <!-- Wrapper for slides -->
    <div class="carousel-inner padHS" role="listbox">
        <?php $i = 1; ?>
        <?php foreach($items as $_item) { ?>
            <?php if ($i % 4 == 1) { ?>
                <div class="item <?= ($i == 1)?' active':'' ?>">
                <div class="row">
            <?php } ?>

            <div class="col-xs-6 col-sm-3">
                <div class="HS-item-wrap">
                    <a href="<?= $block->getProductUrl($_item) ?>">
                        <div class="img-resp img100">
                            <img src="<?= $mediaUrl .'catalog/product'. $_item->getThumbnail()  ?>" />
                        </div>
                        <p><?= $block->escapeHtml($_item->getName()) ?></p>
                        <!-- $block->getProductPrice($_item) ?> -->
                    </a>
                </div>
            </div>
            <?php if ($i % 4 == 0 || $i == $items->getSize()) { ?>
                </div>
                </div>
            <?php } ?>
            <?php $i++; ?>
        <?php } ?>
    </div>
    <!-- Controls -->
    <a href="#relatedSlider" role="button" data-slide="prev">
        <div class="prevButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/left.png"/>
        </div>
    </a>
    <a href="#relatedSlider" role="button" data-slide="next">
        <div class="nextButtonWrap" aria-hidden="true">
            <img src="<?= $mediaUrl ?>images/home/right.png"/>
        </div>
    </a>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function ($) {
        $(document).ready(function ($) {
            $(window).load(function () {
                $('#relatedSlider').carousel({
                    interval: false
                });
            });
        });
    });
</script>
    <?php endif; // related upSell ?>
</div>
<?php endif; // exist ?>


