<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>

<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
?>

<li class="post-holder post-holder-<?= $_post->getId() ?>">
    <div class="post-inner-wrap">
        <div class="post-header">
            <div class="post-title-holder clearfix">
                <div class="addthis_toolbox addthis_default_style" addthis:url="<?= $_postUrl ?>">
                    <a class="addthis_button_facebook"></a>
                    <a class="addthis_button_twitter"></a>
                    <a class="addthis_button_email"></a>
                    <a class="addthis_button_compact"></a>
                </div>
                <p class="post-title">
                    <a class="post-item-link" href="<?= $_postUrl ?>"><?= $_postName; ?></a>
                </p>
            </div>

            <?= $this->getInfoHtml() ?>
        </div>

        <div class="post-content">
            <div class="post-description clearfix">
                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <div class="post-ftimg-hld">
                        <a href="<?= $_postUrl ?>" title="<?= $_postName ?>" class="img-resp img70">
                            <img src="<?= $featuredImage ?>" alt="<?= $_postName ?>"/>
                        </a>
                    </div>
                <?php } ?>
                <div class="post-text-hld clearfix">
                    <?= $block->getShorContent() ?>
                </div>
                <a class="post-read-more" href="<?= $_postUrl ?>" title="<?= $_postName ?>">Read more >></a>
            </div>
        </div>
    </div>
</li>